//
// ApproveGameRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApproveGameRequest: Codable {

    public var gameId: Int

    public init(gameId: Int) {
        self.gameId = gameId
    }

    public enum CodingKeys: String, CodingKey { 
        case gameId = "game_id"
    }

}

