//
// FinishSingleQuizRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FinishSingleQuizRequest: Codable {

    /** Идентификатор игры */
    public var _id: Int
    public var questions: [FinishSingleQuizRequestQuestions]

    public init(_id: Int, questions: [FinishSingleQuizRequestQuestions]) {
        self._id = _id
        self.questions = questions
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case questions
    }

}

