//
// FinishSingleQuizRequestQuestions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FinishSingleQuizRequestQuestions: Codable {

    /** Идентификатор вопроса */
    public var _id: Int
    /** Идентификатор ответа */
    public var answerId: Int

    public init(_id: Int, answerId: Int) {
        self._id = _id
        self.answerId = answerId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case answerId = "answer_id"
    }

}

