//
// MediaResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MediaResource: Codable {

    public var _id: Int?
    public var url: String?

    public init(_id: Int?, url: String?) {
        self._id = _id
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case url
    }

}

