//
// QuizAnswerResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QuizAnswerResource: Codable {

    public var _id: Int?
    public var value: String?
    public var correct: Bool?

    public init(_id: Int?, value: String?, correct: Bool?) {
        self._id = _id
        self.value = value
        self.correct = correct
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case value
        case correct
    }

}

