//
// SetAnswerMultiplayerQuizRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetAnswerMultiplayerQuizRequest: Codable {

    public var gameId: Int
    public var questionId: Int
    public var answerId: Int

    public init(gameId: Int, questionId: Int, answerId: Int) {
        self.gameId = gameId
        self.questionId = questionId
        self.answerId = answerId
    }

    public enum CodingKeys: String, CodingKey { 
        case gameId = "game_id"
        case questionId = "question_id"
        case answerId = "answer_id"
    }

}

