//
// SigninResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SigninResource: Codable {

    public var user: UserResource?
    public var token: TokenResource?

    public init(user: UserResource?, token: TokenResource?) {
        self.user = user
        self.token = token
    }


}

