//
// TokenResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenResource: Codable {

    public var tokenType: String?
    public var expiresIn: Int?
    public var accessToken: String?
    public var refreshToken: String?

    public init(tokenType: String?, expiresIn: Int?, accessToken: String?, refreshToken: String?) {
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.accessToken = accessToken
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey { 
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
    }

}

