//
// UploadRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UploadRequest: Codable {

    public var file: URL
    public var collectionName: String

    public init(file: URL, collectionName: String) {
        self.file = file
        self.collectionName = collectionName
    }

    public enum CodingKeys: String, CodingKey { 
        case file
        case collectionName = "collection_name"
    }

}

