//
// BuyHintRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuyHintRequest: Codable {

    /** Идентификатор игры */
    public var gameId: Int
    /** Идентификатор вопроса */
    public var questionId: Int

    public init(gameId: Int, questionId: Int) {
        self.gameId = gameId
        self.questionId = questionId
    }

    public enum CodingKeys: String, CodingKey { 
        case gameId = "game_id"
        case questionId = "question_id"
    }

}

