//
// FinishGameSingleQuizResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FinishGameSingleQuizResource: Codable {

    public var points: Int?
    public var coins: Int?
    public var lives: Int?

    public init(points: Int?, coins: Int?, lives: Int?) {
        self.points = points
        self.coins = coins
        self.lives = lives
    }


}

