//
// LevelResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LevelResource: Codable {

    public var _id: Int?
    public var number: Int?
    public var points: Int?

    public init(_id: Int?, number: Int?, points: Int?) {
        self._id = _id
        self.number = number
        self.points = points
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case number
        case points
    }

}

