//
// RatingUserResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingUserResource: Codable {

    public var _id: Int?
    public var username: String?
    public var name: String?
    public var position: Int?
    public var points: Int?
    public var avatar: MediaResource?

    public init(_id: Int?, username: String?, name: String?, position: Int?, points: Int?, avatar: MediaResource?) {
        self._id = _id
        self.username = username
        self.name = name
        self.position = position
        self.points = points
        self.avatar = avatar
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case name
        case position
        case points
        case avatar
    }

}

