//
// RatingResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingResource: Codable {

    public var items: [RatingUserResource]?
    public var meta: MetaPaginationResource?
    public var _self: RatingUserResource?

    public init(items: [RatingUserResource]?, meta: MetaPaginationResource?, _self: RatingUserResource?) {
        self.items = items
        self.meta = meta
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey { 
        case items
        case meta
        case _self = "self"
    }

}

