//
// SignupRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SignupRequest: Codable {

    public var name: String
    public var username: String
    public var email: String
    public var password: String

    public init(name: String, username: String, email: String, password: String) {
        self.name = name
        self.username = username
        self.email = email
        self.password = password
    }


}

