//
// StoreMultiplayerQuizRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoreMultiplayerQuizRequest: Codable {

    /** id соперника или null для поиска случайного соперника */
    public var userId: Int

    public init(userId: Int) {
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "user_id"
    }

}

