//
// SubcategoryAllRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubcategoryAllRequest: Codable {

    public var sportId: Int

    public init(sportId: Int) {
        self.sportId = sportId
    }

    public enum CodingKeys: String, CodingKey { 
        case sportId = "sport_id"
    }

}

