//
// TeamAllRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TeamAllRequest: Codable {

    public var subcategoryId: Int

    public init(subcategoryId: Int) {
        self.subcategoryId = subcategoryId
    }

    public enum CodingKeys: String, CodingKey { 
        case subcategoryId = "subcategory_id"
    }

}

