//
// TeamResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TeamResource: Codable {

    public var _id: Int?
    public var name: String?
    public var image: MediaResource?

    public init(_id: Int?, name: String?, image: MediaResource?) {
        self._id = _id
        self.name = name
        self.image = image
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case image
    }

}

