//
// UpdateFirebaseToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateFirebaseToken: Codable {

    public var firebaseToken: String

    public init(firebaseToken: String) {
        self.firebaseToken = firebaseToken
    }

    public enum CodingKeys: String, CodingKey { 
        case firebaseToken = "firebase_token"
    }

}

