//
// UserResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserResource: Codable {

    public var _id: Int?
    public var name: String?
    public var username: String?
    public var email: String?
    public var points: Int?
    public var coins: Int?
    public var lives: Int?
    public var position: Int?
    public var avatar: MediaResource?

    public init(_id: Int?, name: String?, username: String?, email: String?, points: Int?, coins: Int?, lives: Int?, position: Int?, avatar: MediaResource?) {
        self._id = _id
        self.name = name
        self.username = username
        self.email = email
        self.points = points
        self.coins = coins
        self.lives = lives
        self.position = position
        self.avatar = avatar
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case username
        case email
        case points
        case coins
        case lives
        case position
        case avatar
    }

}

