//
// ValidationException.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ValidationException: Codable {

    public var field: String?
    public var message: String?
    public var _description: String?

    public init(field: String?, message: String?, _description: String?) {
        self.field = field
        self.message = message
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case field
        case message
        case _description = "description"
    }

}

